version: '3'
services:
  xray:
    image: amazon/aws-xray-daemon
    command:
      - '--local-mode'
      - '-o'
      - '-n'
      - 'us-west-2'
    ports:
      - 2000:2000/udp
      - 2000:2000/tcp
    volumes:
      - ~/.aws/:/root/.aws/
    environment:
     - AWS_DEFAULT_REGION=us-west-2
     - AWS_XRAY_CONTEXT_MISSING=RUNTIME_ERROR
    networks:
      - robot-shop
  mongodb:
    build:
      context: mongo
    image: ${REPO}/rs-mongodb:${TAG}
    networks:
      - robot-shop
  redis:
    image: redis:4.0.6
    networks:
      - robot-shop
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    networks:
      - robot-shop
  catalogue:
    build:
      context: catalogue
    image: ${REPO}/rs-catalogue:${TAG}
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    networks:
      - robot-shop
  user:
    build:
      context: user
    image: ${REPO}/rs-user:${TAG}
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
    networks:
      - robot-shop
  cart:
    build:
      context: cart
    image: ${REPO}/rs-cart:${TAG}
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    networks:
      - robot-shop
  mysql:
    build:
      context: mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
  shipping:
    build:
      context: shipping
    image: ${REPO}/rs-shipping:${TAG}
    depends_on:
      - mysql
    networks:
      - robot-shop
  ratings:
    build:
      context: ratings
    image: ${REPO}/rs-ratings:${TAG}
    networks:
      - robot-shop
    depends_on:
      - mysql
  payment:
    build:
      context: payment
    image: ${REPO}/rs-payment:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  dispatch:
    build:
      context: dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  web:
    build:
      context: web
      dockerfile: Dockerfile_local
    image: ${REPO}/rs-web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop

networks:
  robot-shop:

