apiVersion: v1
kind: Service
metadata:
  namespace: robotshop
  name: web
  labels:
    service: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    service: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: web
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: web
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/robot-shop/web
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
---
#Horizontal Pod Autoscaler
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: robotshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
#Horizontal Pod Autoscaler
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: web
  namespace: robotshop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: web
  service:
    port: 8080
    trafficPolicy:
      tls:
        mode: DISABLE
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  analysis:
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Istio Prometheus checks
    metrics:
      - name: error-rate
        templateRef:
          name: error-rate
          namespace: robotshop
        thresholdRange:
          max: 1
        interval: 30s
      - name: latency
        templateRef:
          name: latency
          namespace: robotshop
        thresholdRange:
          max: 500
        interval: 30s