apiVersion: v1
kind: Service
metadata:
  namespace: robotshop
  name: dispatch
  labels:
    service: dispatch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: dispatch
  labels:
    service: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: dispatch
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/robot-shop/dispatch
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
