---
# Source: aws-for-fluent-bit/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-aws-for-fluent-bit
  namespace: robotshop
  labels:
    app.kubernetes.io/name: aws-for-fluent-bit
    app.kubernetes.io/instance: robotshop
    app.kubernetes.io/version: "2.2.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-for-fluent-bit
      app.kubernetes.io/instance: robotshop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-for-fluent-bit
        app.kubernetes.io/instance: robotshop
    spec:
      serviceAccountName: fluent-aws-for-fluent-bit
      containers:
        - name: aws-for-fluent-bit
          imagePullPolicy: IfNotPresent
          image: "amazon/aws-for-fluent-bit:2.2.0"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentbit-config
          configMap:
            name: fluent-aws-for-fluent-bit
