apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  namespace: robotshop
  name: payment
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
  selector:
    service: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: payment
  labels:
    app: payment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: payment
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/robot-shop/payment:v.0.1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: 'xray-service.robotshop:2000'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
---
#Horizontal Pod Autoscaler
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: robotshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
#Horizontal Pod Autoscaler
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: payment
  namespace: robotshop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: payment
  service:
    port: 8080
    trafficPolicy:
      tls:
        mode: DISABLE
    gateways:
    - istio-ingressgateway.istio-system.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
    - "*"
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  analysis:
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Istio Prometheus checks
    metrics:
      - name: error-rate
        templateRef:
          name: error-rate
          namespace: robotshop
        thresholdRange:
          max: 1
        interval: 30s
      - name: latency
        templateRef:
          name: latency
          namespace: robotshop
        thresholdRange:
          max: 500
        interval: 30s