apiVersion: v1
kind: Service
metadata:
  namespace: robotshop
  labels:
    service: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: mysql
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: mysql
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/robot-shop/mysql
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
