apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  namespace: robotshop
  name: payment
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: robotshop
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      serviceAccountName: robot-shop
      containers:
      - name: payment
        image: 164382793440.dkr.ecr.us-west-2.amazonaws.com/robot-shop/payment
        imagePullPolicy: Always
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: 'xray-service.robotshop:2000'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
